# Generated by Django 5.0.7 on 2024-08-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_word_testresult_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='average_accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='average_raw_wpm',
            field=models.FloatField(default=0.0),
        ),
    ]
