# Generated by Django 5.0.7 on 2024-08-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_userprofile_average_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='gross_wpm',
            field=models.FloatField(default=0.0),
        ),
    ]
